'use client';

import { useEffect, useRef, useState } from 'react';
import { DropdownControl } from './ui';

export type ImageToolId='compress'|'background'|'resize'|'passport'|'product-clean'|'to-webp'|'webp-png'|'blur-face'|'screenshot'|'profile'|'social-size'|'shadow';
type Tool=ImageToolId;
type ImageInfo={name:string;size:number;type:string;width:number;height:number};
type ExportInfo={size:number;type:string;width:number;height:number};

export const imageToolModules:{id:Tool;name:string;group:string}[]=[
  {id:'compress',name:'Image Compressor',group:'Optimize'},{id:'to-webp',name:'Image to WebP',group:'Optimize'},{id:'webp-png',name:'WebP to PNG',group:'Optimize'},
  {id:'resize',name:'Image Resizer',group:'Resize & Crop'},{id:'passport',name:'Passport Photo Maker',group:'Resize & Crop'},{id:'profile',name:'Profile Picture Cropper',group:'Resize & Crop'},{id:'social-size',name:'Social Media Size Converter',group:'Resize & Crop'},
  {id:'background',name:'Background Remover',group:'Product & Privacy'},{id:'product-clean',name:'Product Image Background Cleaner',group:'Product & Privacy'},{id:'shadow',name:'Product Photo Shadow Generator',group:'Product & Privacy'},{id:'blur-face',name:'Blur Face Tool',group:'Product & Privacy'},
  {id:'screenshot',name:'Screenshot Beautifier',group:'Design'},
];
const tools=imageToolModules;
const c='w-full rounded-xl border border-gray-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-gray-900 focus:ring-2 focus:ring-gray-100';
const btn='rounded-xl bg-gray-950 px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40';
const MAX_IMAGE_BYTES=40*1024*1024;const MAX_SOURCE_PIXELS=50_000_000;const MAX_EXPORT_PIXELS=36_000_000;const MAX_EXPORT_EDGE=6_000;
const formatBytes=(bytes:number)=>bytes<1024*1024?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1024/1024).toFixed(2)} MB`;

export function validateImageFile(file:{name:string;size:number;type:string},width?:number,height?:number){
  if(!['image/jpeg','image/png','image/webp'].includes(file.type))return 'Choose a JPG, PNG or WebP image.';
  if(file.size>MAX_IMAGE_BYTES)return `${file.name} is larger than the ${formatBytes(MAX_IMAGE_BYTES)} limit.`;
  if(width&&height&&width*height>MAX_SOURCE_PIXELS)return `This image contains ${(width*height/1_000_000).toFixed(1)} megapixels. Keep source images at or below ${MAX_SOURCE_PIXELS/1_000_000} megapixels.`;
  return null;
}

function imageFrom(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('The browser could not decode this image.'));image.src=url})}
function canvasBlob(canvas:HTMLCanvasElement,type:string,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('The browser could not create the export.')),type,quality))}

export function ImageToolsStudio({initialTool='compress',embedded=false}:{initialTool?:ImageToolId;embedded?:boolean}={}){
  const[active,setActive]=useState<Tool>(initialTool);const[src,setSrc]=useState('');const[fileName,setFileName]=useState('image');
  const[quality,setQuality]=useState('82');const[width,setWidth]=useState('1200');const[height,setHeight]=useState('1200');const[preset,setPreset]=useState('Instagram square — 1080×1080');
  const[threshold,setThreshold]=useState('38');const[region,setRegion]=useState('30,15,40,40');const[padding,setPadding]=useState('100');const[color,setColor]=useState('#7c3aed');
  const[status,setStatus]=useState('Choose an image to begin.');const[original,setOriginal]=useState<ImageInfo|null>(null);const[output,setOutput]=useState<ExportInfo|null>(null);const[busy,setBusy]=useState(false);
  const[hydrated,setHydrated]=useState(false);useEffect(()=>setHydrated(true),[]);useEffect(()=>{setActive(initialTool);setOutput(null)},[initialTool]);
  const canvas=useRef<HTMLCanvasElement>(null);const groups=Array.from(new Set(tools.map(x=>x.group)));
  const mime=active==='to-webp'||active==='compress'?'image/webp':'image/png';
  const choose=(id:Tool)=>{setActive(id);setOutput(null);setStatus(src?'Configure the option and create a fresh preview.':'Choose an image to begin.')};
  const load=async(file?:File)=>{if(!file)return;setBusy(true);setOutput(null);const initialError=validateImageFile(file);if(initialError){setSrc('');setOriginal(null);setStatus(initialError);setBusy(false);return}const url=URL.createObjectURL(file);try{const image=await imageFrom(url);const dimensionError=validateImageFile(file,image.naturalWidth,image.naturalHeight);if(dimensionError){setSrc('');setOriginal(null);setStatus(dimensionError);return}const reader=new FileReader();const data=await new Promise<string>((resolve,reject)=>{reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('The browser could not read this image.'));reader.readAsDataURL(file)});setSrc(data);setFileName(file.name.replace(/\.[^.]+$/,''));setOriginal({name:file.name,size:file.size,type:file.type,width:image.naturalWidth,height:image.naturalHeight});setStatus(`${file.name} loaded locally at ${image.naturalWidth} × ${image.naturalHeight}px.`)}catch(error){setSrc('');setOriginal(null);setStatus(error instanceof Error?error.message:'Could not load this image.')}finally{URL.revokeObjectURL(url);setBusy(false)}};
  const render=async()=>{const el=canvas.current;if(!el||!src)return null;setBusy(true);setStatus('Rendering a high-quality preview locally…');try{const image=await imageFrom(src);draw(active,image,el,{quality:+quality/100,width:+width,height:+height,preset,threshold:+threshold,region,padding:+padding,color});const blob=await canvasBlob(el,mime,+quality/100);setOutput({size:blob.size,type:mime,width:el.width,height:el.height});setStatus(`Preview ready at ${el.width} × ${el.height}px · ${formatBytes(blob.size)} estimated export.`);return blob}catch(error){setStatus(error instanceof Error?error.message:'Could not render this image.');return null}finally{setBusy(false)}};
  const download=async()=>{const blob=await render();if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${fileName}-${active}.${mime==='image/webp'?'webp':'png'}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),5000);setStatus(`Downloaded ${formatBytes(blob.size)} ${mime==='image/webp'?'WebP':'PNG'} at ${canvas.current?.width} × ${canvas.current?.height}px.`)};
  const saving=original&&output?original.size-output.size:null;
  return <div data-testid="image-tools-studio" data-hydrated={hydrated?'true':'false'} className={embedded?'min-w-0':'grid gap-5 xl:grid-cols-[270px_minmax(0,1fr)]'}>
    {!embedded&&<aside className="self-start rounded-2xl border bg-white p-3 shadow-sm xl:sticky xl:top-4"><div className="px-3 pb-3 pt-2"><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">12 image utilities</p><h2 className="mt-1 text-lg font-bold">Image Tools</h2></div>{groups.map(g=><div key={g} className="mb-3"><p className="px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-gray-400">{g}</p>{tools.filter(x=>x.group===g).map(x=><button key={x.id} onClick={()=>choose(x.id)} className={`mb-1 w-full rounded-xl px-3 py-2 text-left text-sm ${active===x.id?'bg-gray-950 font-semibold text-white':'text-gray-700 hover:bg-gray-100'}`}>{x.name}</button>)}</div>)}</aside>}
    <section className="min-w-0 space-y-5"><header className="rounded-2xl border bg-gradient-to-r from-purple-50 to-pink-50 p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-purple-700">Image Tools</p><h2 className="mt-1 text-2xl font-bold">{tools.find(x=>x.id===active)?.name}</h2><p className="mt-1 text-sm text-gray-600">Your image stays in this browser and is never uploaded.</p></header>
      <div className="grid gap-5 lg:grid-cols-[360px_minmax(0,1fr)]"><section className="space-y-4 rounded-2xl border bg-white p-5"><label className="block"><span className="mb-1 block text-sm font-medium">Choose image</span><input className={c} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>load(e.target.files?.[0])}/></label>
        {['compress','to-webp'].includes(active)&&<Field label="Quality (%)" value={quality} set={setQuality} type="range"/>}
        {active==='resize'&&<div className="grid grid-cols-2 gap-3"><Field label="Width px" value={width} set={setWidth}/><Field label="Height px" value={height} set={setHeight}/></div>}
        {['passport','social-size'].includes(active)&&<label className="block"><span className="mb-1 block text-sm font-medium">Output preset</span><DropdownControl className={c} ariaLabel="Output preset" value={preset} onChange={setPreset} options={active==='passport'?['35×45 mm — 413×531','2×2 inch — 600×600','50×70 mm — 591×827']:['Instagram square — 1080×1080','Instagram portrait — 1080×1350','Story / Reel — 1080×1920','Facebook landscape — 1200×630','YouTube thumbnail — 1280×720','LinkedIn post — 1200×627']}/></label>}
        {['background','product-clean'].includes(active)&&<><Field label="Background tolerance" value={threshold} set={setThreshold} type="range"/><Color label="Background sample color" value={color} set={setColor}/></>}
        {active==='blur-face'&&<Field label="Blur region: x%, y%, width%, height%" value={region} set={setRegion}/>} 
        {active==='screenshot'&&<><Field label="Canvas padding px" value={padding} set={setPadding}/><Color label="Gradient color" value={color} set={setColor}/></>}
        {active==='shadow'&&<Color label="Background color" value={color} set={setColor}/>} 
        <div className="flex flex-wrap gap-2"><button className={btn} disabled={!src||busy} onClick={render}>{busy?'Processing…':'Create preview'}</button><button className="rounded-xl border px-4 py-2.5 text-sm font-semibold disabled:opacity-40" disabled={!src||busy} onClick={download}>Download</button></div>
        <p className="text-xs leading-5 text-gray-500">{active==='background'?'Color-based removal works best on plain, evenly lit backgrounds. Complex scenes require manual or AI refinement.':active==='blur-face'?'Enter the face rectangle as percentages of the image. Review the exported image closely before sharing.':active==='passport'?'Dimensions alone do not guarantee official compliance. Verify head position, background and current authority requirements.':'Preview and export are produced with browser canvas at up to 36 megapixels.'}</p>
        {(original||output)&&<div className="rounded-xl border border-gray-200 bg-gray-50 p-3 text-xs"><p className="font-semibold text-gray-900">Quality diagnostics</p>{original&&<p className="mt-2 text-gray-600">Original: {original.width} × {original.height}px · {formatBytes(original.size)} · {original.type.replace('image/','').toUpperCase()}</p>}{output&&<p className="mt-1 text-gray-600">Export: {output.width} × {output.height}px · {formatBytes(output.size)} · {output.type.replace('image/','').toUpperCase()}</p>}{saving!==null&&<p className={`mt-1 font-medium ${saving>=0?'text-emerald-700':'text-amber-700'}`}>{saving>=0?`${formatBytes(saving)} smaller (${(saving/original!.size*100).toFixed(1)}%)`:`${formatBytes(Math.abs(saving))} larger because of format or dimensions`}</p>}</div>}
        <p role="status" className="rounded-xl bg-gray-100 p-3 text-xs text-gray-700">{status}</p>
      </section><section className="overflow-auto rounded-2xl border bg-[linear-gradient(45deg,#eee_25%,transparent_25%),linear-gradient(-45deg,#eee_25%,transparent_25%),linear-gradient(45deg,transparent_75%,#eee_75%),linear-gradient(-45deg,transparent_75%,#eee_75%)] bg-[length:20px_20px] bg-[position:0_0,0_10px,10px_-10px,-10px_0px] p-5"><canvas ref={canvas} className="mx-auto max-h-[760px] max-w-full bg-white shadow-lg"/></section></div>
    </section>
  </div>;
}

function Field({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="block"><span className="mb-1 block text-sm font-medium">{label}</span><input className={c} type={type} min={type==='range'?1:undefined} max={type==='range'?100:undefined} value={value} onChange={e=>set(e.target.value)}/>{type==='range'&&<span className="mt-1 block text-xs text-gray-500">{value}%</span>}</label>}
function Color({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="block"><span className="mb-1 block text-sm font-medium">{label}</span><input type="color" value={value} onChange={e=>set(e.target.value)} className="h-12 w-full rounded-xl border p-1"/></label>}
const sizes:Record<string,[number,number]>={'35×45 mm — 413×531':[413,531],'2×2 inch — 600×600':[600,600],'50×70 mm — 591×827':[591,827],'Instagram square — 1080×1080':[1080,1080],'Instagram portrait — 1080×1350':[1080,1350],'Story / Reel — 1080×1920':[1080,1920],'Facebook landscape — 1200×630':[1200,630],'YouTube thumbnail — 1280×720':[1280,720],'LinkedIn post — 1200×627':[1200,627]};
function cover(ctx:CanvasRenderingContext2D,img:HTMLImageElement,w:number,h:number){const s=Math.max(w/img.width,h/img.height),dw=img.width*s,dh=img.height*s;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh)}
function hex(v:string){return[parseInt(v.slice(1,3),16),parseInt(v.slice(3,5),16),parseInt(v.slice(5,7),16)]}
function removeColor(ctx:CanvasRenderingContext2D,w:number,h:number,color:string,tolerance:number,clean=false){const data=ctx.getImageData(0,0,w,h),[r,g,b]=hex(color);for(let i=0;i<data.data.length;i+=4){const d=Math.sqrt((data.data[i]-r)**2+(data.data[i+1]-g)**2+(data.data[i+2]-b)**2);if(d<tolerance*(clean?2.2:1.5)){const alpha=Math.min(255,Math.max(0,(d-tolerance*.35)/(tolerance*1.15)*255));data.data[i+3]=alpha}}ctx.putImageData(data,0,0)}
function draw(tool:Tool,img:HTMLImageElement,el:HTMLCanvasElement,o:{quality:number;width:number;height:number;preset:string;threshold:number;region:string;padding:number;color:string}){let w=img.width,h=img.height;if(tool==='resize'){w=Math.max(1,o.width);h=Math.max(1,o.height)}if(['passport','social-size'].includes(tool))[w,h]=sizes[o.preset];if(tool==='profile')w=h=Math.min(img.width,img.height,2400);if(tool==='screenshot'){w=img.width+o.padding*2;h=img.height+o.padding*2}if(tool==='shadow'){w=img.width+160;h=img.height+160}const scale=Math.min(1,MAX_EXPORT_EDGE/Math.max(w,h),Math.sqrt(MAX_EXPORT_PIXELS/(w*h)));w=Math.max(1,Math.round(w*scale));h=Math.max(1,Math.round(h*scale));el.width=w;el.height=h;const ctx=el.getContext('2d',{alpha:true})!;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.clearRect(0,0,w,h);if(tool==='screenshot'){const grad=ctx.createLinearGradient(0,0,w,h);grad.addColorStop(0,o.color);grad.addColorStop(1,'#ec4899');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.shadowColor='rgba(0,0,0,.35)';ctx.shadowBlur=35;ctx.shadowOffsetY=18;ctx.drawImage(img,o.padding*scale,o.padding*scale,img.width*scale,img.height*scale);return}if(tool==='shadow'){ctx.fillStyle=o.color;ctx.fillRect(0,0,w,h);ctx.shadowColor='rgba(0,0,0,.3)';ctx.shadowBlur=35;ctx.shadowOffsetY=25;ctx.drawImage(img,80*scale,50*scale,img.width*scale,img.height*scale);return}if(tool==='profile'){ctx.save();ctx.beginPath();ctx.arc(w/2,h/2,w/2,0,Math.PI*2);ctx.clip();cover(ctx,img,w,h);ctx.restore();return}if(['passport','social-size'].includes(tool))cover(ctx,img,w,h);else ctx.drawImage(img,0,0,w,h);if(['background','product-clean'].includes(tool))removeColor(ctx,w,h,o.color,o.threshold,tool==='product-clean');if(tool==='blur-face'){const[x,y,rw,rh]=o.region.split(',').map(Number);const sx=w*x/100,sy=h*y/100,sw=w*rw/100,sh=h*rh/100;ctx.save();ctx.filter='blur(22px)';ctx.drawImage(el,sx,sy,sw,sh,sx-15,sy-15,sw+30,sh+30);ctx.restore()}}
