'use client';

import { useEffect, useRef, useState } from 'react';
import { DropdownControl } from './ui';

type Template='corporate'|'geometric'|'elegant'|'bold'|'minimal';
type Draft={template:Template;paper:'A4'|'Letter';mode:'letter'|'blank';primary:string;secondary:string;company:string;tagline:string;address:string;phone:string;email:string;website:string;recipient:string;recipientDetails:string;date:string;reference:string;subject:string;body:string;sender:string;designation:string;logo:string;watermark:string;signature:string;watermarkOpacity:string};
const initial:Draft={template:'geometric',paper:'A4',mode:'letter',primary:'#173f73',secondary:'#f59e0b',company:'Your Company',tagline:'Ideas. Service. Results.',address:'House 57, Road 22, Dhaka, Bangladesh',phone:'+880 1700-000000',email:'hello@example.com',website:'https://example.com',recipient:'Recipient Name',recipientDetails:'Company Name\nStreet address\nCity, Country',date:new Date().toISOString().slice(0,10),reference:'REF-001',subject:'Subject of your business letter',body:'Dear Recipient,\n\nUse this space for your formal business letter. The layout preserves generous writing space while keeping your identity visible and consistent.\n\nAdd additional paragraphs as needed. The exported PDF is designed for professional email delivery and office printing.\n\nSincerely,',sender:'Your Name',designation:'Managing Director',logo:'',watermark:'',signature:'',watermarkOpacity:'8'};
const input='w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm outline-none focus:border-gray-900 focus:ring-2 focus:ring-gray-100';
const templates:Template[]=['corporate','geometric','elegant','bold','minimal'];
const labels:Record<Template,string>={corporate:'Corporate',geometric:'Geometric',elegant:'Elegant',bold:'Bold',minimal:'Minimal'};
const urlOk=(value:string)=>!value||/^https?:\/\//i.test(value);

export function LetterheadDesigner(){
  const [draft,setDraft]=useState<Draft>(initial);const [scale,setScale]=useState(1);const [busy,setBusy]=useState(false);const holder=useRef<HTMLDivElement>(null);const fileRefs={logo:useRef<HTMLInputElement>(null),watermark:useRef<HTMLInputElement>(null),signature:useRef<HTMLInputElement>(null)};
  const width=draft.paper==='A4'?794:816,height=draft.paper==='A4'?1123:1056;
  useEffect(()=>{try{const saved=localStorage.getItem('contra-letterhead-draft');if(saved)setDraft({...initial,...JSON.parse(saved)})}catch{}},[]);
  useEffect(()=>{const id=setTimeout(()=>localStorage.setItem('contra-letterhead-draft',JSON.stringify(draft)),300);return()=>clearTimeout(id)},[draft]);
  useEffect(()=>{const el=holder.current;if(!el)return;const update=()=>setScale(Math.min(1,el.clientWidth/width));update();const observer=new ResizeObserver(update);observer.observe(el);return()=>observer.disconnect()},[width]);
  const patch=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft((old)=>({...old,[key]:value}));
  const upload=(key:'logo'|'watermark'|'signature',file?:File)=>{if(!file)return;if(!file.type.startsWith('image/')||file.size>2_000_000){alert('Choose a PNG, JPG, WebP, or SVG smaller than 2 MB.');return}const reader=new FileReader();reader.onload=()=>patch(key,String(reader.result||''));reader.readAsDataURL(file)};
  const capture=async()=>{const paper=document.querySelector<HTMLElement>('[data-letterhead-paper]');if(!paper)throw new Error('Preview is unavailable.');const previous=paper.style.transform;paper.style.transform='none';try{await document.fonts.ready;const {default:html2canvas}=await import('html2canvas');return await html2canvas(paper,{scale:3,useCORS:true,backgroundColor:'#fff',logging:false})}finally{paper.style.transform=previous}};
  const downloadPdf=async()=>{setBusy(true);try{const canvas=await capture();const {jsPDF}=await import('jspdf');const format=draft.paper==='A4'?'a4':'letter';const pdf=new jsPDF({unit:'mm',format,orientation:'portrait'});const pw=pdf.internal.pageSize.getWidth(),ph=pdf.internal.pageSize.getHeight();pdf.addImage(canvas.toDataURL('image/png'),'PNG',0,0,pw,ph,undefined,'FAST');if(urlOk(draft.website)&&draft.website)pdf.link(12,ph-13,65,6,{url:draft.website});if(draft.email)pdf.link(80,ph-13,55,6,{url:`mailto:${draft.email}`});pdf.save(`${draft.company.replace(/[^a-z0-9]+/gi,'-').toLowerCase()||'company'}-letterhead.pdf`)}finally{setBusy(false)}};
  const print=async()=>{const popup=window.open('','_blank','width=950,height=900');if(!popup){alert('Allow pop-ups to print the letterhead.');return}popup.document.write('<p style="font-family:Arial;padding:20px">Preparing print preview…</p>');try{const canvas=await capture(),image=canvas.toDataURL('image/png');popup.document.open();popup.document.write(`<!doctype html><html><head><title>${draft.company} Letterhead</title><style>@page{size:auto;margin:10mm}html,body{margin:0}img{display:block;width:100%;height:auto;-webkit-print-color-adjust:exact;print-color-adjust:exact}</style></head><body><img src="${image}" onload="setTimeout(()=>print(),60)"></body></html>`);popup.document.close()}catch{popup.close();alert('Could not prepare print preview.')}};
  const valid=urlOk(draft.website);
  return <div className="min-w-0 space-y-5 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-gray-200 bg-gray-50 p-3"><div><b className="text-sm text-gray-900">Professional Letterhead Designer</b><p className="text-xs text-gray-500">Draft saves automatically on this device</p></div><div className="flex gap-2"><button onClick={print} className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-xs font-semibold">Print</button><button disabled={busy||!valid} onClick={downloadPdf} className="rounded-lg bg-gray-950 px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{busy?'Creating PDF…':'Download PDF'}</button></div></div><div className="grid min-w-0 items-start gap-5"><section className="order-last min-w-0 space-y-5 overflow-hidden rounded-2xl border border-gray-200 bg-white p-4 sm:p-5">
    <Block title="Choose a design"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{templates.map((item)=><button key={item} onClick={()=>patch('template',item)} className={`min-w-0 rounded-lg border p-2 text-[10px] font-semibold ${draft.template===item?'border-gray-950 bg-gray-950 text-white':'border-gray-200 text-gray-600'}`}><span style={{background:`linear-gradient(135deg,${draft.primary} 55%,${draft.secondary} 55%)`}} className="mb-1 block h-8 rounded"/><span className="block truncate">{labels[item]}</span></button>)}</div><div className="grid gap-3 sm:grid-cols-2"><Select label="Paper" value={draft.paper} set={(v)=>patch('paper',v as Draft['paper'])} options={['A4','Letter']}/><Select label="Document mode" value={draft.mode} set={(v)=>patch('mode',v as Draft['mode'])} options={[['letter','Completed letter'],['blank','Blank letterhead']]}/></div><div className="grid gap-3 sm:grid-cols-2"><Color label="Primary" value={draft.primary} set={(v)=>patch('primary',v)}/><Color label="Secondary" value={draft.secondary} set={(v)=>patch('secondary',v)}/></div></Block>
    <Block title="Company identity"><Field label="Company name" value={draft.company} set={(v)=>patch('company',v)}/><Field label="Tagline" value={draft.tagline} set={(v)=>patch('tagline',v)}/><Area label="Address" value={draft.address} set={(v)=>patch('address',v)} rows={2}/><div className="grid grid-cols-2 gap-3"><Field label="Phone" value={draft.phone} set={(v)=>patch('phone',v)}/><Field label="Email" value={draft.email} set={(v)=>patch('email',v)} type="email"/></div><Field label="Website" value={draft.website} set={(v)=>patch('website',v)} type="url" error={!valid?'Use a complete http:// or https:// URL.':''}/></Block>
    <Block title="Brand images"><Upload label="Company logo" image={draft.logo} click={()=>fileRefs.logo.current?.click()} remove={()=>patch('logo','')}/><input hidden ref={fileRefs.logo} type="file" accept="image/*" onChange={(e)=>upload('logo',e.target.files?.[0])}/><Upload label="Watermark" image={draft.watermark} click={()=>fileRefs.watermark.current?.click()} remove={()=>patch('watermark','')}/><input hidden ref={fileRefs.watermark} type="file" accept="image/*" onChange={(e)=>upload('watermark',e.target.files?.[0])}/>{draft.watermark&&<Field label="Watermark opacity (%)" value={draft.watermarkOpacity} set={(v)=>patch('watermarkOpacity',v)} type="number"/>}<Upload label="Signature image" image={draft.signature} click={()=>fileRefs.signature.current?.click()} remove={()=>patch('signature','')}/><input hidden ref={fileRefs.signature} type="file" accept="image/*" onChange={(e)=>upload('signature',e.target.files?.[0])}/></Block>
    {draft.mode==='letter'&&<><Block title="Recipient and reference"><Field label="Recipient" value={draft.recipient} set={(v)=>patch('recipient',v)}/><Area label="Recipient details" value={draft.recipientDetails} set={(v)=>patch('recipientDetails',v)} rows={3}/><div className="grid grid-cols-2 gap-3"><Field label="Date" value={draft.date} set={(v)=>patch('date',v)} type="date"/><Field label="Reference" value={draft.reference} set={(v)=>patch('reference',v)}/></div><Field label="Subject" value={draft.subject} set={(v)=>patch('subject',v)}/></Block><Block title="Letter content"><Area label="Body" value={draft.body} set={(v)=>patch('body',v)} rows={10}/><div className="grid grid-cols-2 gap-3"><Field label="Sender name" value={draft.sender} set={(v)=>patch('sender',v)}/><Field label="Designation" value={draft.designation} set={(v)=>patch('designation',v)}/></div></Block></>}
  </section><section className="order-first min-w-0 overflow-hidden rounded-2xl bg-gray-100 p-3 sm:p-5"><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-bold text-gray-900">Live preview</h3><span className="text-xs text-gray-500">{draft.paper} · {labels[draft.template]}</span></div><div ref={holder} style={{height:height*scale,maxWidth:width,width:'100%'}} className="mx-auto overflow-hidden"><LetterheadPaper draft={draft} width={width} height={height} scale={scale}/></div></section></div></div>;
}

function LetterheadPaper({draft,width,height,scale}:{draft:Draft;width:number;height:number;scale:number}){const geometric=draft.template==='geometric',bold=draft.template==='bold',elegant=draft.template==='elegant',minimal=draft.template==='minimal';return <article data-letterhead-paper style={{width,height,transform:`scale(${scale})`,transformOrigin:'top left',fontFamily:elegant?'Georgia,serif':'Arial,sans-serif'}} className="relative overflow-hidden bg-white text-[#20242b] shadow-xl">
  {geometric&&<><i style={{background:draft.primary}} className="absolute left-0 right-0 top-0 h-3"/><i style={{background:draft.secondary}} className="absolute right-0 top-3 h-2 w-[32%]"/><i style={{background:draft.primary}} className="absolute left-0 top-3 h-28 w-3"/><i style={{background:draft.secondary}} className="absolute left-3 top-3 h-16 w-2"/><i style={{background:draft.primary}} className="absolute bottom-0 right-0 h-24 w-3"/><i style={{background:draft.secondary}} className="absolute bottom-0 right-3 h-12 w-2"/></>}{bold&&<><i style={{background:draft.primary}} className="absolute left-0 top-0 h-full w-5"/><i style={{background:draft.secondary}} className="absolute bottom-0 left-0 h-8 w-full"/></>}{elegant&&<div style={{borderColor:draft.primary}} className="absolute inset-8 border"/>}{minimal&&<div style={{background:draft.primary}} className="absolute left-12 right-12 top-32 h-px"/>}
  <header style={draft.template==='corporate'?{background:draft.primary,color:'white'}:{}} className={`relative z-10 flex items-start justify-between gap-8 ${draft.template==='corporate'?'px-14 py-10':'px-14 pt-12'}`}><div className="flex max-w-[58%] items-center gap-4">{draft.logo?<img src={draft.logo} alt="Logo" className="max-h-20 max-w-36 object-contain"/>:<div style={{background:draft.secondary,color:draft.primary}} className="grid h-16 w-16 shrink-0 place-items-center text-xl font-black">{draft.company.slice(0,2).toUpperCase()}</div>}<div><h2 className="text-2xl font-bold leading-tight">{draft.company}</h2><p className={`mt-1 text-[11px] ${draft.template==='corporate'?'text-white/75':'text-gray-500'}`}>{draft.tagline}</p></div></div><div style={geometric?{borderColor:draft.secondary}:{}} className={`max-w-[38%] text-right text-[10px] leading-4 ${draft.template==='corporate'?'text-white/80':geometric?'border-l-2 pl-3 text-gray-600':'text-gray-500'}`}><p>{draft.phone}</p><p>{draft.email}</p><p className="break-all">{draft.website}</p></div></header>
  {draft.watermark&&<img src={draft.watermark} alt="" style={{opacity:Math.max(0,Math.min(30,Number(draft.watermarkOpacity)||0))/100}} className="absolute left-1/2 top-1/2 z-0 max-h-[42%] max-w-[50%] -translate-x-1/2 -translate-y-1/2 object-contain"/>}
  {draft.mode==='letter'&&<main className="relative z-10 px-16 pb-32 pt-16 text-[12px] leading-[1.65]"><div className="flex justify-between gap-12"><div><b className="block text-[13px]">{draft.recipient}</b><p className="whitespace-pre-line text-gray-500">{draft.recipientDetails}</p></div><dl className="shrink-0 text-right text-[10px]"><div><dt className="inline font-bold">Date: </dt><dd className="inline">{draft.date}</dd></div><div><dt className="inline font-bold">Reference: </dt><dd className="inline">{draft.reference}</dd></div></dl></div><h3 style={{color:draft.primary,borderColor:draft.secondary}} className="mt-8 border-b pb-2 text-[14px] font-bold">{draft.subject}</h3><p className="mt-6 whitespace-pre-line">{draft.body}</p><div className="mt-7">{draft.signature&&<img src={draft.signature} alt="Signature" className="mb-1 max-h-14 max-w-32 object-contain"/>}<b className="block">{draft.sender}</b><span className="text-gray-500">{draft.designation}</span></div></main>}
  <footer className={`absolute left-0 right-0 z-20 px-14 ${elegant?'bottom-8':bold?'bottom-7':geometric?'bottom-4':'bottom-0 pb-6'}`}><div style={{borderColor:draft.secondary}} className={`flex items-start justify-between gap-5 border-t px-3 py-2 text-[10px] leading-4 text-gray-600 ${elegant||bold?'bg-white/95':''}`}><p className="max-w-[48%]">{draft.address}</p><p className="max-w-[48%] text-right"><span>{draft.phone} &nbsp; • &nbsp; {draft.email}</span><span className="block break-all">{draft.website}</span></p></div></footer>
  </article>}
function Block({title,children}:{title:string;children:React.ReactNode}){return <fieldset className="min-w-0 space-y-3 border-b border-gray-100 pb-5"><legend className="mb-3 text-sm font-bold text-gray-900">{title}</legend>{children}</fieldset>}
function Field({label,value,set,type='text',error}:{label:string;value:string;set:(v:string)=>void;type?:string;error?:string}){return <label className="block min-w-0"><span className="mb-1 block text-xs font-medium text-gray-600">{label}</span><input className={`${input} min-w-0 ${error?'border-red-400':''}`} type={type} value={value} onChange={(e)=>set(e.target.value)}/>{error&&<span className="mt-1 block text-xs text-red-600">{error}</span>}</label>}
function Area({label,value,set,rows}:{label:string;value:string;set:(v:string)=>void;rows:number}){return <label className="block"><span className="mb-1 block text-xs font-medium text-gray-600">{label}</span><textarea className={input} rows={rows} value={value} onChange={(e)=>set(e.target.value)}/></label>}
function Select({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:Array<string|[string,string]>}){return <label className="block"><span className="mb-1 block text-xs font-medium text-gray-600">{label}</span><DropdownControl className={input} ariaLabel={label} value={value} onChange={set} options={options.map(o=>{const[value,label]=typeof o==='string'?[o,o]:o;return{value,label}})}/></label>}
function Color({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="min-w-0"><span className="mb-1 block text-xs font-medium text-gray-600">{label}</span><div className="flex min-w-0 gap-2"><input type="color" value={value} onChange={(e)=>set(e.target.value)} className="h-10 w-12 shrink-0 rounded border p-1"/><input value={value} onChange={(e)=>set(e.target.value)} className={`${input} min-w-0 font-mono uppercase`}/></div></label>}
function Upload({label,image,click,remove}:{label:string;image:string;click:()=>void;remove:()=>void}){return <div><span className="mb-1 block text-xs font-medium text-gray-600">{label}</span><div className="flex items-center gap-2">{image&&<img src={image} alt="" className="h-10 w-16 rounded border bg-white object-contain"/>}<button onClick={click} className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-xs font-semibold">{image?'Replace':'Choose image'}</button>{image&&<button onClick={remove} className="text-xs text-red-600">Remove</button>}</div></div>}
