'use client';

import { useState } from 'react';
import { LetterheadDesigner } from './LetterheadDesigner';
import { DropdownControl } from './ui';

type Mode = 'merge'|'split'|'editor'|'compress'|'images-to-pdf'|'pdf-to-images'|'numbering'|'margin'|'signature'|'form'|'bank-cleaner'|'resume'|'letterhead'|'certificate'|'minutes'|'proposal'|'compare';
type DocumentMode = 'resume'|'certificate'|'minutes'|'proposal';
type DocumentLanguage = 'en'|'bn';
type GeneratedDocument = {title:string;name:string;subtitle:string;body:string;accent:string;date:string;website:string;github:string;drive:string};
const modes: Array<{id:Mode;label:string;group:string}> = [
  {id:'merge',label:'Merge PDFs',group:'PDF editor'},{id:'split',label:'Split / extract',group:'PDF editor'},{id:'editor',label:'Rotate / remove / reorder',group:'PDF editor'},{id:'compress',label:'Optimize PDF',group:'PDF editor'},
  {id:'images-to-pdf',label:'Images to PDF',group:'Convert'},{id:'pdf-to-images',label:'PDF to images',group:'Convert'},
  {id:'numbering',label:'Page numbering',group:'Pages'},{id:'margin',label:'Margin adder / fixer',group:'Pages'},{id:'signature',label:'Signature tool',group:'Pages'},{id:'form',label:'Form filler',group:'Pages'},
  {id:'bank-cleaner',label:'Bank statement cleaner',group:'Specialized'},{id:'compare',label:'Compare documents',group:'Specialized'},
  {id:'resume',label:'Resume to PDF',group:'Generate'},{id:'letterhead',label:'Letterhead',group:'Generate'},{id:'certificate',label:'Certificate',group:'Generate'},{id:'minutes',label:'Meeting minutes',group:'Generate'},{id:'proposal',label:'Branded proposal',group:'Generate'},
];
const modeHelp: Record<Mode,string> = {
  merge:'Combine multiple PDF files into one document in the order selected.',
  split:'Extract selected pages or page ranges into a new PDF.',
  editor:'Keep, remove, reorder and rotate pages without changing their visible quality.',
  compress:'Clean metadata and optimize the PDF object structure without lowering image quality.',
  'images-to-pdf':'Place JPG or PNG images onto print-ready PDF pages.',
  'pdf-to-images':'Render every PDF page as high-resolution PNG or JPEG images and download a ZIP.',
  numbering:'Add consistent page numbers at your chosen corner or edge.',
  margin:'Scale and centre each page inside a safe printer margin while preserving its paper size.',
  signature:'Stamp a PNG or JPEG signature image onto selected PDF pages.',
  form:'Complete existing fillable text fields and flatten them into a shareable copy.',
  'bank-cleaner':'Remove metadata, flatten fields and retain only the statement pages you choose; transaction data is never altered.',
  compare:'Compare the extracted text of two PDFs and list sentences that were added, removed or changed.',
  resume:'Generate a professional PDF résumé with optional clickable website, GitHub and portfolio links.',
  letterhead:'Design a branded, multi-colour letterhead with a live print-ready preview.',
  certificate:'Create a branded certificate of achievement with recipient, title, date and message.',
  minutes:'Turn meeting notes, decisions and actions into a clean PDF record.',
  proposal:'Create a branded proposal PDF with author, date, overview and structured content.',
};
const input='w-full rounded-xl border border-gray-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-gray-900 focus:ring-2 focus:ring-gray-100';
const button='rounded-xl bg-gray-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-gray-800 disabled:cursor-not-allowed disabled:opacity-50';
const MAX_FILE_BYTES=75*1024*1024;const MAX_TOTAL_BYTES=150*1024*1024;const MAX_FILES=20;
const mm=(value:number)=>value*72/25.4;
const safeName=(name:string)=>name.replace(/\.pdf$/i,'').replace(/[^a-z0-9_-]+/gi,'-').replace(/^-|-$/g,'')||'document';
const formatBytes=(bytes:number)=>bytes<1024*1024?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;
const documentCopy={
  en:{language:'English',title:'Document title',name:'Name / organization',subtitle:'Subtitle',content:'Content',date:'Document date',heading:{resume:'Professional profile',certificate:'Certificate of achievement',minutes:'Meeting minutes',proposal:'Proposal overview'}},
  bn:{language:'বাংলা',title:'ডকুমেন্টের শিরোনাম',name:'নাম / প্রতিষ্ঠান',subtitle:'উপশিরোনাম',content:'বিস্তারিত লেখা',date:'ডকুমেন্টের তারিখ',heading:{resume:'পেশাগত পরিচিতি',certificate:'অর্জনের সনদ',minutes:'সভা কার্যবিবরণী',proposal:'প্রস্তাবনার সারসংক্ষেপ'}},
} as const;
export function documentPreset(mode:DocumentMode,language:DocumentLanguage,date=new Date().toISOString().slice(0,10)):GeneratedDocument{
  const presets={
    en:{resume:{title:'Professional Resume',name:'Your Name',subtitle:'Professional title and summary',body:'PROFILE\nWrite a focused professional summary.\n\nEXPERIENCE\nRole — Company — Dates\nDescribe measurable responsibilities and achievements.\n\nEDUCATION\nDegree — Institution — Year\n\nSKILLS\nAdd relevant skills separated by commas.'},certificate:{title:'Certificate of Achievement',name:'Recipient Name',subtitle:'Presented in recognition of outstanding achievement',body:'This certificate is proudly presented for commitment, excellence, and successful completion.'},minutes:{title:'Meeting Minutes',name:'Organization or meeting owner',subtitle:'Meeting topic · location or online',body:'ATTENDEES\nList attendees and roles.\n\nAGENDA\n1. First agenda item\n2. Second agenda item\n\nDECISIONS\nRecord decisions and their owners.\n\nACTION ITEMS\nOwner — Task — Due date\n\nNEXT MEETING\nAdd the proposed date and time.'},proposal:{title:'Project Proposal',name:'Your company or author',subtitle:'Prepared for client or project name',body:'EXECUTIVE SUMMARY\nState the client need and your proposed outcome.\n\nSCOPE\nList the work and deliverables.\n\nTIMELINE\nDescribe phases and target dates.\n\nINVESTMENT\nAdd pricing, payment schedule, and validity.\n\nNEXT STEPS\nExplain how the client can approve and begin.'}},
    bn:{resume:{title:'পেশাগত জীবনবৃত্তান্ত',name:'আপনার নাম',subtitle:'পেশাগত পদবি ও সংক্ষিপ্ত পরিচিতি',body:'পেশাগত পরিচিতি\nআপনার দক্ষতা ও অভিজ্ঞতার সংক্ষিপ্ত বিবরণ লিখুন।\n\nকর্ম-অভিজ্ঞতা\nপদবি — প্রতিষ্ঠান — সময়কাল\nদায়িত্ব ও পরিমাপযোগ্য অর্জন লিখুন।\n\nশিক্ষাগত যোগ্যতা\nডিগ্রি — প্রতিষ্ঠান — সাল\n\nদক্ষতা\nপ্রাসঙ্গিক দক্ষতাগুলো কমা দিয়ে লিখুন।'},certificate:{title:'অর্জনের সনদ',name:'প্রাপকের নাম',subtitle:'বিশেষ অর্জনের স্বীকৃতিস্বরূপ প্রদান করা হলো',body:'নিষ্ঠা, উৎকর্ষ এবং সফল সম্পন্নতার স্বীকৃতিস্বরূপ এই সনদ প্রদান করা হলো।'},minutes:{title:'সভা কার্যবিবরণী',name:'প্রতিষ্ঠান বা সভার আয়োজক',subtitle:'সভার বিষয় · স্থান বা অনলাইন',body:'উপস্থিত সদস্য\nসদস্যদের নাম ও দায়িত্ব লিখুন।\n\nআলোচ্যসূচি\n১. প্রথম আলোচ্য বিষয়\n২. দ্বিতীয় আলোচ্য বিষয়\n\nসিদ্ধান্ত\nগৃহীত সিদ্ধান্ত ও দায়িত্বপ্রাপ্ত ব্যক্তি লিখুন।\n\nকরণীয় কাজ\nদায়িত্বপ্রাপ্ত — কাজ — শেষ তারিখ\n\nপরবর্তী সভা\nপ্রস্তাবিত তারিখ ও সময় লিখুন।'},proposal:{title:'প্রকল্প প্রস্তাবনা',name:'আপনার প্রতিষ্ঠান বা নাম',subtitle:'ক্লায়েন্ট বা প্রকল্পের জন্য প্রস্তুত',body:'নির্বাহী সারসংক্ষেপ\nক্লায়েন্টের প্রয়োজন এবং প্রস্তাবিত ফলাফল লিখুন।\n\nকাজের পরিধি\nকাজ ও ডেলিভারেবলগুলো তালিকাভুক্ত করুন।\n\nসময়সূচি\nধাপ ও সম্ভাব্য তারিখ লিখুন।\n\nবিনিয়োগ\nমূল্য, পেমেন্ট সময়সূচি এবং প্রস্তাবের মেয়াদ লিখুন।\n\nপরবর্তী পদক্ষেপ\nঅনুমোদন ও কাজ শুরুর প্রক্রিয়া লিখুন।'}},
  } as const;
  return {...presets[language][mode],accent:'#111827',date,website:'',github:'',drive:''};
}
export function generatedDocumentError(doc:GeneratedDocument,mode:DocumentMode){
  if(!doc.title.trim())return 'Add a document title.';
  if(!doc.name.trim())return mode==='certificate'?'Add the certificate recipient.':'Add a name or organization.';
  if(!doc.body.trim())return 'Add document content.';
  if(doc.body.length>12000)return 'Keep document content below 12,000 characters.';
  if(mode==='resume'&&![doc.website,doc.github,doc.drive].every(validHttpUrl))return 'Professional links must begin with http:// or https://.';
  return null;
}
export function validateDocumentFiles(files:Array<{name:string;size:number;type:string}>,acceptImages=false){
  if(!files.length)return 'Choose at least one file.';
  if(files.length>MAX_FILES)return `Choose no more than ${MAX_FILES} files at once.`;
  const oversized=files.find(file=>file.size>MAX_FILE_BYTES);if(oversized)return `${oversized.name} is larger than the ${formatBytes(MAX_FILE_BYTES)} per-file limit.`;
  const total=files.reduce((sum,file)=>sum+file.size,0);if(total>MAX_TOTAL_BYTES)return `The selected files total ${formatBytes(total)}. Keep one operation below ${formatBytes(MAX_TOTAL_BYTES)}.`;
  const invalid=files.find(file=>acceptImages?!['image/jpeg','image/png'].includes(file.type):file.type!=='application/pdf');if(invalid)return acceptImages?'Only JPG and PNG images are supported.':'Only PDF files are supported.';
  return null;
}
function download(bytes:Uint8Array,name:string,type='application/pdf'){const blob=new Blob([new Uint8Array(bytes)],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function parsePages(value:string,total:number){const pages=new Set<number>();for(const part of value.split(',')){const [a,b]=part.trim().split('-').map(Number);if(!a)continue;for(let i=a;i<=(b||a);i++)if(i>=1&&i<=total)pages.add(i-1)}return [...pages]}
async function pdfjs(){const lib=await import('pdfjs-dist/legacy/build/pdf.mjs');if(!lib.GlobalWorkerOptions.workerSrc)lib.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/legacy/build/pdf.worker.min.mjs',import.meta.url).toString();return lib}
async function extractText(file:File){const lib=await pdfjs();const doc=await lib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;const pages:string[]=[];for(let i=1;i<=doc.numPages;i++){const page=await doc.getPage(i);const content=await page.getTextContent();pages.push(content.items.map((item)=>'str'in item?item.str:'').join(' '))}return pages}
async function renderBanglaDocument(doc:GeneratedDocument,mode:DocumentMode){
  const {default:html2canvas}=await import('html2canvas');
  const page=document.createElement('article');
  Object.assign(page.style,{position:'fixed',left:'-10000px',top:'0',width:'794px',height:'1123px',boxSizing:'border-box',padding:mode==='certificate'?'74px':'68px',overflow:'hidden',background:'#fff',color:'#20242b',fontFamily:'var(--font-hind-siliguri), "Hind Siliguri", sans-serif'});
  if(mode==='certificate')page.style.border=`10px double ${doc.accent}`;
  const header=document.createElement('div');Object.assign(header.style,{background:mode==='certificate'?'transparent':doc.accent,color:mode==='certificate'?doc.accent:'#fff',margin:mode==='certificate'?'0':'-68px -68px 42px',padding:mode==='certificate'?'36px 0 12px':'38px 68px 30px',textAlign:mode==='certificate'?'center':'left',fontSize:mode==='certificate'?'26px':'30px',fontWeight:'700'});header.textContent=mode==='resume'?doc.name:doc.title;page.append(header);
  const subtitle=document.createElement('div');Object.assign(subtitle.style,{fontSize:mode==='certificate'?'21px':'17px',fontWeight:'600',textAlign:mode==='certificate'?'center':'left',marginTop:mode==='certificate'?'40px':'0'});subtitle.textContent=doc.subtitle;page.append(subtitle);
  if(mode==='certificate'){const recipient=document.createElement('h1');Object.assign(recipient.style,{fontSize:'44px',textAlign:'center',margin:'65px 0 25px',color:'#111827'});recipient.textContent=doc.name;page.append(recipient)}
  else {const meta=document.createElement('p');Object.assign(meta.style,{fontSize:'15px',color:'#6b7280',margin:'12px 0 14px'});meta.textContent=`${doc.name}  ·  ${doc.date}`;page.append(meta);if(mode==='resume'){const links=document.createElement('div');Object.assign(links.style,{fontSize:'13px',color:'#2563eb',lineHeight:'1.7',marginBottom:'20px'});links.textContent=[doc.website,doc.github,doc.drive].filter(Boolean).join('  ·  ');page.append(links)}}
  const body=document.createElement('div');Object.assign(body.style,{whiteSpace:'pre-wrap',fontSize:mode==='certificate'?'18px':'16px',lineHeight:'1.65',textAlign:mode==='certificate'?'center':'left',margin:mode==='certificate'?'40px auto 0':'20px 0',maxWidth:mode==='certificate'?'620px':'none'});body.textContent=doc.body;page.append(body);
  if(mode==='certificate'){const date=document.createElement('p');Object.assign(date.style,{position:'absolute',bottom:'105px',left:'0',right:'0',textAlign:'center',fontSize:'16px'});date.textContent=doc.date;page.append(date)}
  document.body.append(page);try{await document.fonts.ready;return await html2canvas(page,{scale:2,backgroundColor:'#ffffff',useCORS:true})}finally{page.remove()}
}

export function PdfDocumentStudio({ invoiceUrl='/invoice-generator' }: { invoiceUrl?:string }) {
  const [mode,setMode]=useState<Mode>('merge'); const [files,setFiles]=useState<File[]>([]); const [busy,setBusy]=useState(false); const [status,setStatus]=useState('');
  const [optimization,setOptimization]=useState<{before:number;after:number}|null>(null);
  const [range,setRange]=useState('1'); const [margin,setMargin]=useState('12'); const [rotation,setRotation]=useState('90'); const [position,setPosition]=useState('Bottom right'); const [signature,setSignature]=useState<File|null>(null);
  const [formFields,setFormFields]=useState<Array<{name:string;value:string}>>([]); const [documentLanguage,setDocumentLanguage]=useState<DocumentLanguage>('en'); const [doc,setDoc]=useState<GeneratedDocument>(()=>documentPreset('resume','en')); const [comparison,setComparison]=useState('');
  const [imageDpi,setImageDpi]=useState('300'); const [imageFormat,setImageFormat]=useState('PNG'); const [pagePreviews,setPagePreviews]=useState<Array<{url:string;name:string;width:number;height:number}>>([]);
  const groups=[...new Set(modes.map((item)=>item.group))]; const primary=files[0];
  const selectMode=(next:Mode)=>{setMode(next);setFiles([]);setStatus('');setOptimization(null);if(['resume','certificate','minutes','proposal'].includes(next))setDoc(documentPreset(next as DocumentMode,documentLanguage))};
  const changeDocumentLanguage=(language:DocumentLanguage)=>{setDocumentLanguage(language);if(['resume','certificate','minutes','proposal'].includes(mode))setDoc(documentPreset(mode as DocumentMode,language,doc.date))};
  const chooseFiles=(selected:File[],images=false)=>{pagePreviews.forEach((page)=>URL.revokeObjectURL(page.url));setPagePreviews([]);setOptimization(null);setComparison('');const error=validateDocumentFiles(selected,images);if(error){setFiles([]);setStatus(error);return}setFiles(selected);setStatus(`${selected.length} file${selected.length===1?'':'s'} ready · ${formatBytes(selected.reduce((sum,file)=>sum+file.size,0))} total.`)};
  const fileInput=(multiple=false,accept='application/pdf')=><label className="block"><span className="mb-1 block text-sm font-medium text-gray-700">{multiple?'Choose files':'Choose file'}</span><input className={input} type="file" multiple={multiple} accept={accept} onChange={(e)=>chooseFiles(Array.from(e.target.files||[]),accept!=='application/pdf')}/></label>;
  const run=async()=>{setBusy(true);setStatus('Working locally…');try{const {PDFDocument,rgb,degrees,StandardFonts}=await import('pdf-lib');
    if(mode==='merge'){const out=await PDFDocument.create();for(const file of files){const src=await PDFDocument.load(await file.arrayBuffer());const copied=await out.copyPages(src,src.getPageIndices());copied.forEach((p)=>out.addPage(p))}download(await out.save({useObjectStreams:true}),'merged-document.pdf')}
    else if(mode==='split'){if(!primary)return;const src=await PDFDocument.load(await primary.arrayBuffer());const indexes=parsePages(range,src.getPageCount());const out=await PDFDocument.create();(await out.copyPages(src,indexes)).forEach((p)=>out.addPage(p));download(await out.save(),`${safeName(primary.name)}-pages.pdf`)}
    else if(mode==='editor'){if(!primary)return;const src=await PDFDocument.load(await primary.arrayBuffer());const order=parsePages(range,src.getPageCount());const chosen=order.length?order:src.getPageIndices();const out=await PDFDocument.create();const copied=await out.copyPages(src,chosen);copied.forEach((p)=>{p.setRotation(degrees((p.getRotation().angle+Number(rotation))%360));out.addPage(p)});download(await out.save(),`${safeName(primary.name)}-edited.pdf`)}
    else if(mode==='compress'){if(!primary)return;const src=await PDFDocument.load(await primary.arrayBuffer());src.setTitle('');src.setAuthor('');src.setSubject('');src.setKeywords([]);src.setProducer('Contra PDF Studio');const optimized=await src.save({useObjectStreams:true,addDefaultPage:false});setOptimization({before:primary.size,after:optimized.length});download(optimized,`${safeName(primary.name)}-optimized.pdf`)}
    else if(mode==='images-to-pdf'){const out=await PDFDocument.create();for(const file of files){const bytes=await file.arrayBuffer();const image=file.type==='image/png'?await out.embedPng(bytes):await out.embedJpg(bytes);const page=out.addPage([595.28,841.89]);const scale=Math.min((page.getWidth()-mm(20))/image.width,(page.getHeight()-mm(20))/image.height);page.drawImage(image,{x:(page.getWidth()-image.width*scale)/2,y:(page.getHeight()-image.height*scale)/2,width:image.width*scale,height:image.height*scale})}download(await out.save(),'images.pdf')}
    else if(mode==='pdf-to-images'){if(!primary)return;pagePreviews.forEach((page)=>URL.revokeObjectURL(page.url));setPagePreviews([]);const [{default:JSZip},lib]=await Promise.all([import('jszip'),pdfjs()]);const loaded=await lib.getDocument({data:new Uint8Array(await primary.arrayBuffer())}).promise;const zip=new JSZip();const previews:Array<{url:string;name:string;width:number;height:number}>=[];const png=imageFormat==='PNG',extension=png?'png':'jpg',mime=png?'image/png':'image/jpeg';for(let i=1;i<=loaded.numPages;i++){setStatus(`Rendering page ${i} of ${loaded.numPages} at ${imageDpi} DPI…`);const page=await loaded.getPage(i);const viewport=page.getViewport({scale:Number(imageDpi)/72});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const context=canvas.getContext('2d',{alpha:false})!;context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);await page.render({canvas,canvasContext:context,viewport}).promise;const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob((value)=>value?resolve(value):reject(new Error('Could not render this page.')),mime,png?undefined:.98));const name=`${safeName(primary.name)}-page-${String(i).padStart(2,'0')}.${extension}`;zip.file(name,blob);previews.push({url:URL.createObjectURL(blob),name,width:canvas.width,height:canvas.height});canvas.width=1;canvas.height=1}setPagePreviews(previews);const archive=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});downloadBlob(archive,`${safeName(primary.name)}-${imageDpi}dpi-images.zip`)}
    else if(mode==='numbering'){if(!primary)return;const src=await PDFDocument.load(await primary.arrayBuffer());const font=await src.embedFont(StandardFonts.Helvetica);src.getPages().forEach((p,i)=>{const text=`${i+1} / ${src.getPageCount()}`;const size=10,x=position.includes('right')?p.getWidth()-font.widthOfTextAtSize(text,size)-mm(12):position.includes('left')?mm(12):(p.getWidth()-font.widthOfTextAtSize(text,size))/2;const y=position.includes('Top')?p.getHeight()-mm(12):mm(9);p.drawText(text,{x,y,size,font,color:rgb(.25,.27,.3)})});download(await src.save(),`${safeName(primary.name)}-numbered.pdf`)}
    else if(mode==='margin'){if(!primary)return;const src=await PDFDocument.load(await primary.arrayBuffer());const out=await PDFDocument.create();for(const p of src.getPages()){const {width,height}=p.getSize();const target=out.addPage([width,height]);const [embedded]=await out.embedPages([p]);const m=Math.min(mm(Number(margin)||0),Math.min(width,height)*.45);const scale=Math.max(.1,Math.min((width-m*2)/width,(height-m*2)/height));target.drawPage(embedded,{x:(width-width*scale)/2,y:(height-height*scale)/2,width:width*scale,height:height*scale})}download(await out.save(),`${safeName(primary.name)}-margin-fixed.pdf`)}
    else if(mode==='signature'){if(!primary||!signature)return;const src=await PDFDocument.load(await primary.arrayBuffer());const bytes=await signature.arrayBuffer();const sig=signature.type==='image/png'?await src.embedPng(bytes):await src.embedJpg(bytes);const targets=range.toLowerCase()==='all'?src.getPages():parsePages(range,src.getPageCount()).map((i)=>src.getPage(i));for(const p of targets){const w=Math.min(mm(45),p.getWidth()*.3),h=w*sig.height/sig.width;p.drawImage(sig,{x:p.getWidth()-w-mm(14),y:mm(16),width:w,height:h})}download(await src.save(),`${safeName(primary.name)}-signed.pdf`)}
    else if(mode==='form'){if(!primary)return;const src=await PDFDocument.load(await primary.arrayBuffer());const form=src.getForm();for(const item of formFields){try{form.getTextField(item.name).setText(item.value)}catch{}}form.flatten();download(await src.save(),`${safeName(primary.name)}-filled.pdf`)}
    else if(mode==='bank-cleaner'){if(!primary)return;const src=await PDFDocument.load(await primary.arrayBuffer());src.setTitle('Clean bank statement');src.setAuthor('');src.setCreator('');src.setSubject('');src.setKeywords([]);try{src.getForm().flatten()}catch{}const selected=parsePages(range,src.getPageCount());if(selected.length&&selected.length<src.getPageCount()){const out=await PDFDocument.create();(await out.copyPages(src,selected)).forEach((p)=>out.addPage(p));download(await out.save({useObjectStreams:true}),`${safeName(primary.name)}-clean.pdf`)}else download(await src.save({useObjectStreams:true}),`${safeName(primary.name)}-clean.pdf`)}
    else if(mode==='compare'){if(files.length<2)return;const [a,b]=await Promise.all([extractText(files[0]),extractText(files[1])]);const aa=a.join('\n').split(/\n|(?<=[.!?])\s+/),bb=b.join('\n').split(/\n|(?<=[.!?])\s+/);const removed=aa.filter((line)=>line.trim()&&!bb.includes(line)),added=bb.filter((line)=>line.trim()&&!aa.includes(line));setComparison(`REMOVED / CHANGED\n${removed.map((x)=>`- ${x}`).join('\n')||'None'}\n\nADDED / CHANGED\n${added.map((x)=>`+ ${x}`).join('\n')||'None'}`)}
    else {const generatorMode=mode as DocumentMode;const validation=generatedDocumentError(doc,generatorMode);if(validation){setStatus(validation);return}const {jsPDF}=await import('jspdf');const pdf=new jsPDF({unit:'mm',format:'a4'});if(documentLanguage==='bn'){const canvas=await renderBanglaDocument(doc,generatorMode);pdf.addImage(canvas.toDataURL('image/jpeg',.97),'JPEG',0,0,210,297,undefined,'FAST');if(mode==='resume'){[doc.website,doc.github,doc.drive].filter(Boolean).forEach((url,index)=>pdf.link(15,252+index*8,180,7,{url}))}pdf.save(`${mode}-${safeName(doc.title)}.pdf`)}else{const accent=doc.accent;pdf.setFillColor(accent);if(mode==='certificate'){pdf.setLineWidth(2);pdf.setDrawColor(accent);pdf.rect(12,12,186,273);pdf.setFontSize(14);pdf.text(documentCopy.en.heading.certificate.toUpperCase(),105,55,{align:'center'});pdf.setFontSize(30);pdf.text(doc.name,105,100,{align:'center'});pdf.setFontSize(14);pdf.text(doc.subtitle,105,118,{align:'center',maxWidth:160});pdf.setFontSize(11);pdf.text(doc.body,105,150,{align:'center',maxWidth:150});pdf.text(doc.date,105,220,{align:'center'})}else{pdf.setFillColor(accent);pdf.rect(0,0,210,24,'F');pdf.setTextColor(255);pdf.setFontSize(18);pdf.text(mode==='resume'?doc.name:doc.title,16,15);pdf.setTextColor(30);pdf.setFontSize(11);pdf.text(mode==='resume'?doc.subtitle:`${doc.name}  |  ${doc.date}`,16,34);let dividerY=39;if(mode==='resume'){const links=[['Website',doc.website],['GitHub',doc.github],['Portfolio / Drive',doc.drive]].filter((item)=>item[1]);pdf.setFontSize(9);pdf.setTextColor(37,99,235);links.forEach(([label,url],index)=>pdf.textWithLink(`${label}: ${url}`,16,41+index*5,{url}));pdf.setTextColor(30);dividerY=links.length?44+(links.length-1)*5:39}pdf.setDrawColor(accent);pdf.line(16,dividerY,194,dividerY);pdf.setFontSize(12);pdf.setFont('helvetica','bold');pdf.text(documentCopy.en.heading[generatorMode],16,dividerY+12);pdf.setFont('helvetica','normal');pdf.setFontSize(10.5);pdf.text(doc.body,16,dividerY+22,{maxWidth:178,lineHeightFactor:1.5})}pdf.save(`${mode}-${safeName(doc.title)}.pdf`)}}
    setStatus(mode==='compare'?'Comparison ready.':'Download created successfully.');
  }catch(error){setStatus(error instanceof Error?error.message:'Could not process this document.')}finally{setBusy(false)}};
  const inspectForm=async(file:File)=>{const error=validateDocumentFiles([file]);if(error){setFiles([]);setFormFields([]);setStatus(error);return}setFiles([file]);setStatus(`Inspecting ${file.name} locally…`);try{const {PDFDocument}=await import('pdf-lib');const pdf=await PDFDocument.load(await file.arrayBuffer());const detected=pdf.getForm().getFields().map((f)=>({name:f.getName(),value:''}));setFormFields(detected);setStatus(detected.length?`${detected.length} fillable field${detected.length===1?'':'s'} detected.`:'No supported fillable text fields were found.')}catch{setFormFields([]);setStatus('This PDF could not be opened or its form structure is unsupported.')}};
  const isLetterhead=mode==='letterhead'; const isGenerator=['resume','certificate','minutes','proposal'].includes(mode);
  return <div className="grid gap-5 lg:grid-cols-[270px_minmax(0,1fr)]"><aside className="rounded-2xl border border-gray-200 bg-white p-3 shadow-sm">{groups.map((group)=><div key={group} className="mb-4"><p className="px-2 pb-1 text-[10px] font-bold uppercase tracking-[.16em] text-gray-400">{group}</p>{modes.filter((m)=>m.group===group).map((m)=><button key={m.id} onClick={()=>selectMode(m.id)} className={`mb-1 w-full rounded-lg px-3 py-2 text-left text-sm ${mode===m.id?'bg-gray-950 font-semibold text-white':'text-gray-600 hover:bg-gray-100'}`}>{m.label}</button>)}</div>)}</aside><section className={`rounded-2xl border border-gray-200 bg-white shadow-sm ${isLetterhead?'p-3':'p-5'}`}><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-600">PDF & Document Studio</p><h2 className="mt-1 text-xl font-bold text-gray-950">{modes.find((m)=>m.id===mode)?.label}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-gray-600">{modeHelp[mode]}</p></div><p className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-700">Local processing</p></div>{isLetterhead?<LetterheadDesigner/>:<div className="space-y-4">
    {mode==='merge'&&fileInput(true)}{mode==='split'&&<>{fileInput()}<Text label="Pages to extract" value={range} set={setRange} help="Examples: 1-3, 5, 8-10"/></>}{mode==='editor'&&<>{fileInput()}<Text label="New page order / pages to keep" value={range} set={setRange} help="Example: 3, 1, 2. Omitted pages are removed."/><Choice label="Rotate selected pages" value={rotation} set={setRotation} options={['0','90','180','270']}/></>}{mode==='compress'&&<>{fileInput()}<Info>Optimizes the PDF object structure and removes unnecessary metadata. It preserves visual quality; image-heavy PDFs may see modest savings.</Info>{optimization&&<OptimizationReport before={optimization.before} after={optimization.after}/>}</>}
    {mode==='images-to-pdf'&&fileInput(true,'image/jpeg,image/png')}{mode==='pdf-to-images'&&<>{fileInput()}<div className="grid gap-3 sm:grid-cols-2"><Choice label="Output resolution" value={imageDpi} set={setImageDpi} options={['150','300','450']}/><Choice label="Image format" value={imageFormat} set={setImageFormat} options={['PNG','JPEG']}/></div><Info><b>{imageDpi} DPI:</b> {imageDpi==='150'?'Good for screens and smaller files.':imageDpi==='300'?'Print-quality output and the recommended default.':'Extra-high detail for zooming, OCR, and professional printing.'} PNG is lossless; JPEG uses 98% quality.</Info>{pagePreviews.length>0&&<div><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold text-gray-900">High-resolution preview</h3><span className="text-xs text-gray-500">{pagePreviews.length} pages</span></div><div className="grid max-h-[720px] gap-4 overflow-y-auto rounded-xl bg-gray-100 p-4 sm:grid-cols-2">{pagePreviews.map((page)=><figure key={page.name} className="overflow-hidden rounded-lg bg-white p-2 shadow-sm"><img src={page.url} alt={page.name} className="h-auto w-full"/><figcaption className="mt-2 flex justify-between gap-2 text-[10px] text-gray-500"><span className="truncate">{page.name}</span><span className="shrink-0">{page.width} × {page.height}</span></figcaption></figure>)}</div></div>}</>}{mode==='numbering'&&<>{fileInput()}<Choice label="Number position" value={position} set={setPosition} options={['Bottom center','Bottom left','Bottom right','Top center','Top left','Top right']}/></>}{mode==='margin'&&<>{fileInput()}<Text label="Safe margin (mm)" value={margin} set={setMargin}/></>}
    {mode==='signature'&&<>{fileInput()}<label className="block"><span className="mb-1 block text-sm font-medium">Signature image</span><input className={input} type="file" accept="image/png,image/jpeg" onChange={(e)=>{const file=e.target.files?.[0];if(!file)return setSignature(null);const error=validateDocumentFiles([file],true);if(error){setSignature(null);setStatus(error)}else{setSignature(file);setStatus(`Signature image ready · ${formatBytes(file.size)}.`)}}}/></label><Text label="Pages" value={range} set={setRange} help="Use all or a range such as 1,3-5"/></>}
    {mode==='form'&&<><label className="block"><span className="mb-1 block text-sm font-medium">Fillable PDF</span><input className={input} type="file" accept="application/pdf" onChange={(e)=>e.target.files?.[0]&&inspectForm(e.target.files[0])}/></label>{formFields.length?formFields.map((f,i)=><Text key={f.name} label={f.name} value={f.value} set={(value)=>setFormFields((old)=>old.map((x,j)=>j===i?{...x,value}:x))}/>):<Info>Choose a PDF containing fillable text fields. Filled fields will be flattened into the exported copy.</Info>}</>}
    {mode==='bank-cleaner'&&<>{fileInput()}<Text label="Pages to keep" value={range} set={setRange} help="Example: 1-6. Leave invalid to keep all pages."/><Info>Creates a clean shareable copy, removes document metadata, flattens form fields, and keeps only the selected statement pages. It does not alter transaction values.</Info></>}
    {mode==='compare'&&<>{fileInput(true)}<Info>Select exactly two text-based PDFs. The comparison identifies sentences present in only one document.</Info>{comparison&&<textarea className={`${input} font-mono`} rows={16} readOnly value={comparison}/>}</>}
    {isGenerator&&<><div className="grid gap-3 sm:grid-cols-2"><Choice label="Document language" value={documentLanguage} set={(value)=>changeDocumentLanguage(value as DocumentLanguage)} options={['en','bn']}/><Text label={documentCopy[documentLanguage].date} value={doc.date} set={(date)=>setDoc({...doc,date})}/></div><Info>Choose English or বাংলা for this generated document only. Changing language loads a complete mode-specific template.</Info><Text label={documentCopy[documentLanguage].title} value={doc.title} set={(title)=>setDoc({...doc,title})}/><Text label={mode==='certificate'?(documentLanguage==='bn'?'সনদপ্রাপকের নাম':'Certificate recipient'):documentCopy[documentLanguage].name} value={doc.name} set={(name)=>setDoc({...doc,name})}/><Text label={documentCopy[documentLanguage].subtitle} value={doc.subtitle} set={(subtitle)=>setDoc({...doc,subtitle})}/>{mode==='resume'&&<div className="rounded-xl border border-gray-200 bg-gray-50 p-4"><h3 className="mb-3 text-sm font-semibold text-gray-900">{documentLanguage==='bn'?'ক্লিকযোগ্য পেশাগত লিংক':'Clickable professional links'}</h3><div className="space-y-3"><UrlText label="Website URL" value={doc.website} set={(website)=>setDoc({...doc,website})}/><UrlText label="GitHub URL" value={doc.github} set={(github)=>setDoc({...doc,github})}/><UrlText label="Portfolio or Drive URL" value={doc.drive} set={(drive)=>setDoc({...doc,drive})}/></div><p className="mt-3 text-xs text-gray-500">{documentLanguage==='bn'?'ঐচ্ছিক লিংক অবশ্যই http:// অথবা https:// দিয়ে শুরু হবে এবং PDF-এ ক্লিক করা যাবে।':'Optional links must start with http:// or https:// and will be clickable in the PDF.'}</p></div>}<label className="block"><span className="mb-1 block text-sm font-medium">{documentCopy[documentLanguage].content}</span><textarea className={input} rows={14} value={doc.body} onChange={(e)=>setDoc({...doc,body:e.target.value})}/><span className="mt-1 block text-right text-xs text-gray-400">{doc.body.length.toLocaleString()} / 12,000</span></label><label className="block"><span className="mb-1 block text-sm font-medium">{documentLanguage==='bn'?'ব্র্যান্ডের রং':'Brand color'}</span><input type="color" value={doc.accent} onChange={(e)=>setDoc({...doc,accent:e.target.value})} className="h-11 w-20 rounded border p-1"/></label>{generatedDocumentError(doc,mode as DocumentMode)&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{generatedDocumentError(doc,mode as DocumentMode)}</p>}</>}
    {files.length>0&&<div className="rounded-xl border border-gray-200 bg-gray-50 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-semibold uppercase tracking-wider text-gray-500">Selected locally</p><span className="text-xs text-gray-500">{files.length} file{files.length===1?'':'s'} · {formatBytes(files.reduce((sum,file)=>sum+file.size,0))}</span></div><ul className="mt-2 max-h-32 space-y-1 overflow-auto">{files.map((file,index)=><li key={`${file.name}-${index}`} className="flex justify-between gap-3 text-xs text-gray-700"><span className="truncate">{index+1}. {file.name}</span><span className="shrink-0 text-gray-500">{formatBytes(file.size)}</span></li>)}</ul><p className="mt-2 text-[11px] text-gray-500">Files remain in this browser tab. Maximum: {MAX_FILES} files, {formatBytes(MAX_FILE_BYTES)} each, {formatBytes(MAX_TOTAL_BYTES)} total.</p></div>}
    <button className={button} disabled={busy||(!isGenerator&&!files.length)||mode==='compare'&&files.length<2||isGenerator&&Boolean(generatedDocumentError(doc,mode as DocumentMode))} onClick={run}>{busy?(mode==='pdf-to-images'?status||'Rendering pages…':'Processing…'):mode==='compare'?'Compare PDFs':mode==='pdf-to-images'?'Create previews and download ZIP':'Create and download'}</button>{status&&(!busy||mode!=='pdf-to-images')&&<p className="rounded-xl bg-gray-50 p-3 text-sm text-gray-600">{status}</p>}
    <div className="mt-8 border-t border-gray-200 pt-5"><h3 className="text-sm font-semibold text-gray-900">Specialized commerce documents</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><a href={invoiceUrl} className="rounded-xl border border-gray-200 p-4 hover:border-gray-500"><b className="block text-sm">Invoice PDF Generator</b><span className="text-xs text-gray-500">Branded invoices with A4/A5 PDF export</span></a><a href={invoiceUrl} className="rounded-xl border border-gray-200 p-4 hover:border-gray-500"><b className="block text-sm">Printable Packing List</b><span className="text-xs text-gray-500">Open the invoice tool and select Packing slip</span></a></div></div>
  </div>}</section></div>;
}
function Text({label,value,set,help}:{label:string;value:string;set:(v:string)=>void;help?:string}){return <label className="block"><span className="mb-1 block text-sm font-medium text-gray-700">{label}</span><input className={input} value={value} onChange={(e)=>set(e.target.value)}/>{help&&<span className="mt-1 block text-xs text-gray-400">{help}</span>}</label>}
function Choice({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[]}){return <label className="block"><span className="mb-1 block text-sm font-medium text-gray-700">{label}</span><DropdownControl className={input} ariaLabel={label} value={value} onChange={set} options={options.map(o=>({value:o,label:label==='Document language'?(o==='bn'?'বাংলা':'English'):o}))}/></label>}
function Info({children}:{children:React.ReactNode}){return <p className="rounded-xl border border-blue-100 bg-blue-50 p-3 text-sm leading-6 text-blue-800">{children}</p>}
function validHttpUrl(value:string){if(!value)return true;try{const url=new URL(value);return url.protocol==='http:'||url.protocol==='https:'}catch{return false}}
function UrlText({label,value,set}:{label:string;value:string;set:(v:string)=>void}){const valid=validHttpUrl(value);return <label className="block"><span className="mb-1 block text-xs font-medium text-gray-700">{label}</span><input type="url" inputMode="url" className={`${input} ${valid?'':'border-red-400 focus:border-red-500 focus:ring-red-100'}`} value={value} placeholder="https://example.com" onChange={(e)=>set(e.target.value)}/>{!valid&&<span className="mt-1 block text-xs text-red-600">Enter a complete URL beginning with http:// or https://</span>}</label>}
function OptimizationReport({before,after}:{before:number;after:number}){const saved=before-after,pct=before?saved/before*100:0,reduced=saved>0,format=(bytes:number)=>bytes<1024*1024?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1024/1024).toFixed(2)} MB`;return <div className={`rounded-2xl border p-4 ${reduced?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-semibold uppercase tracking-wider text-gray-500">Optimization result</p><p className={`mt-1 text-lg font-bold ${reduced?'text-emerald-800':'text-amber-800'}`}>{reduced?`${pct.toFixed(1)}% smaller`:'Already optimized - no size reduction'}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${reduced?'bg-emerald-200 text-emerald-900':'bg-amber-200 text-amber-900'}`}>{reduced?'Reduced':'No reduction'}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-sm"><div><span className="block text-xs text-gray-500">Original</span><b>{format(before)}</b></div><div><span className="block text-xs text-gray-500">Optimized</span><b>{format(after)}</b></div><div><span className="block text-xs text-gray-500">Saved</span><b>{reduced?format(saved):'0 KB'}</b></div></div>{!reduced&&<p className="mt-3 text-xs leading-5 text-amber-800">The file structure and metadata were cleaned, but the resulting file is not smaller. The source PDF was likely already optimized.</p>}</div>}
